channels = ["conda-forge"]

[deps]
python = "3.12.*"
numpy = ">=2.2"
shapely = ">=2.1"
trimesh = ">=4.6"
rtree = ">=1.4"
scipy = ">=1.15"
meshio = ">=5.3"
rasterio = ">=1.4.3"
open3d = { version = "==0.19.0", build = "*_0" }

[pip.deps]
pysplashsurf = "==0.12.0.1"