channels = ["conda-forge", "anaconda"]

[deps]
numpy = ">=2.2"
shapely = ">=2.1"
open3d = ">=0.19"
trimesh = ">=4.6"
rtree = ">=1.4"
scipy = ">=1.15"
meshio = ">=5.3"

[pip.deps]
rasterio = "==1.4.1"
pysplashsurf = "==0.12.0.1"