name = "FastPointQuery"
uuid = "b325ad68-3eea-4afa-b43e-4b8e378fd76d"
authors = ["Zenan Huo <zenan.huo@outlook.com>"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2"
PythonCall = "0.9"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]